# syntax=docker/dockerfile:1

FROM node:20-alpine AS deps
WORKDIR /app


COPY package*.json ./
RUN npm ci --omit=dev

FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NODE_OPTIONS=--enable-source-maps

COPY --from=deps /app/node_modules ./node_modules

COPY dist/apps/api-service ./dist/apps/api-service
COPY dist/libs ./dist/libs

COPY package.json ./


USER node

EXPOSE 3002

CMD ["node", "dist/apps/api-service/main.js"]
